In [101]:
import torch

In [102]:
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [103]:
x_2 = inputs[1]
print(x_2)

tensor([0.5500, 0.8700, 0.6600])


In [104]:
d_in = inputs.shape[1]
d_out = 2

In [105]:
torch.manual_seed(123)

In [106]:
W_query = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad = False)
print(W_query.shape)
print(W_query)

torch.Size([3, 2])
Parameter containing:
tensor([[-0.1115,  0.1204],
        [-0.3696, -0.2404],
        [-1.1969,  0.2093]])


In [107]:
W_key = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad = False)
print(W_key.shape)
print(W_key)

torch.Size([3, 2])
Parameter containing:
tensor([[-0.9724, -0.7550],
        [ 0.3239, -0.1085],
        [ 0.2103, -0.3908]])


In [108]:
W_value = torch.nn.Parameter(torch.randn(d_in, d_out), requires_grad = False)
print(W_value.shape)
print(W_value)

torch.Size([3, 2])
Parameter containing:
tensor([[ 0.2350,  0.6653],
        [ 0.3528,  0.9728],
        [-0.0386, -0.8861]])


In [109]:
query_2 = torch.matmul(x_2, W_query)
print(query_2.shape)
print(query_2)

torch.Size([2])
tensor([-1.1729, -0.0048])


In [110]:
key_2 = torch.matmul(x_2, W_key)
print(key_2.shape)
print(key_2)

torch.Size([2])
tensor([-0.1142, -0.7676])


In [111]:
value_2 = torch.matmul(x_2, W_value)
print(value_2.shape)
print(value_2)

torch.Size([2])
tensor([0.4107, 0.6274])


In [112]:
keys = torch.matmul(inputs, W_key)
print(key.shape)
print(key)

torch.Size([6, 2])
tensor([[-0.1823, -0.6888],
        [-0.1142, -0.7676],
        [-0.1443, -0.7728],
        [ 0.0434, -0.3580],
        [-0.6467, -0.6476],
        [ 0.3262, -0.3395]])


In [113]:
values = torch.matmul(inputs, W_value)
print(value.shape)
print(value)

torch.Size([6, 2])
tensor([[ 0.1196, -0.3566],
        [ 0.4107,  0.6274],
        [ 0.4091,  0.6390],
        [ 0.2436,  0.4182],
        [ 0.2653,  0.6668],
        [ 0.2728,  0.3242]])


In [114]:
keys_2 = keys[1]
attention_score_22 = torch.dot(query_2, keys_2)
print(attention_score_22)

tensor(0.1376)


In [115]:
attention_score_2 = torch.matmul(query_2, keys.T)
print(attention_score_2)

tensor([ 0.2172,  0.1376,  0.1730, -0.0491,  0.7616, -0.3809])


In [116]:
d_k = keys.shape[-1]
print(d_k)

2


In [118]:
attention_weights_2 = torch.softmax(attention_score_2 / torch.sqrt(torch.tensor(d_k, dtype=torch.float32)), dim=-1)
print(attention_weights_2)

tensor([0.1704, 0.1611, 0.1652, 0.1412, 0.2505, 0.1117])


In [119]:
context_vec_2 = torch.matmul(attention_weights_2, values)
print(context_vec_2)

tensor([0.2854, 0.4081])
