In [ ]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
import torch

In [8]:
import os
os.chdir("/media/mistertandon/DATA/git_repos/ai/01-llm-rsbt/settings")

In [9]:
with open("the-verdict.txt", "r", encoding = "utf-8") as f:
    raw_text = f.read()
print(f"length of raw text: {len(raw_text)} characters")

length of raw text: 20479 characters


In [10]:
import sys
sys.path.insert(0, '/media/mistertandon/DATA/git_repos/ai/01-llm-rsbt/ch_02')

from ch02_26_data_sampling import GPTDatasetV1, create_dataloader_v1

In [11]:
vocab_size = 50257
output_dim = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(token_embedding_layer)

Embedding(50257, 256)


In [12]:
max_length = 4
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=max_length, shuffle=False, drop_last=True, num_workers=2)
data_iter = iter(dataloader)

In [13]:
inputs, targets = next(data_iter)

In [14]:
print("Token IDs: ", inputs)
print("Input shape: ", inputs.shape)

Token IDs:  tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Input shape:  torch.Size([8, 4])


In [15]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [16]:

element = token_embeddings[0, 0, 0]
print(element)

tensor(2.1137, grad_fn=<SelectBackward0>)


In [17]:
element_10 = token_embeddings[0, 0, :10]
print(element_10)

tensor([ 2.1137,  1.4168,  1.3451,  1.5862, -0.4985, -0.3735,  0.4960, -0.3900,
         0.3788,  0.8425], grad_fn=<SliceBackward0>)


In [18]:
context_length = max_length
position_embedding_layer = torch.nn.Embedding(context_length, output_dim)
print(position_embedding_layer)

Embedding(4, 256)


In [19]:
position_embeddings = position_embedding_layer(torch.arange(context_length))
print(position_embeddings.shape)

torch.Size([4, 256])


In [20]:
position_embeddings[0].shape

torch.Size([256])

In [21]:
position_embeddings[0, :10]

tensor([-0.9456,  1.6102, -0.6928, -0.3387, -0.9409, -0.2009, -0.6866, -0.8755,
         1.2682,  0.1506], grad_fn=<SliceBackward0>)

In [22]:
input_embeddings = token_embeddings + position_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [23]:
input_embeddings[0,0].shape

torch.Size([256])

In [24]:
input_embeddings[0,0, :10]

tensor([ 1.1682,  3.0270,  0.6523,  1.2475, -1.4393, -0.5744, -0.1905, -1.2655,
         1.6470,  0.9931], grad_fn=<SliceBackward0>)